#!/usr/bin/env python
#
# this is a fake robot, network table server..
#

import time, sys
from networktables import NetworkTables
import comm

def visValueChanged(table, key, value, isNew):
    global dirty
    visTable[key] = value
    visTable["count"] += 1
    dirty = True
    # for fast updates this print can slow things down:
    # print("%s:%s" % (key, value))

def main():
    # To see messages from networktables, you must setup logging
    import logging
    logging.basicConfig(level=logging.DEBUG)
    NetworkTables.initialize() # we're the fake robot server
    vis = comm.getVisionTable()
    vis.addTableListener(visValueChanged)
    visTable = {} 
    dirty = False
    visTable["count"] = 0
    i = 0
    while True:
        time.sleep(1)
        i += 1
        if dirty:
            print(visTable)
            visTable["count"] = 0
            dirty = False

if __name__ == "__main__":
    main() 
