#!/usr/bin/env python3
#
# this is a fake robot, network table server..
#

import time, sys
import logging
import networktables

dirty = False
visTable = {} 

def visTargetChanged(table, key, value, isNew):
    global visTable
    global dirty
    visTable[key] = value
    visTable["count"] += 1
    dirty = True
    # for fast updates this print can slow things down:
    # print("%s:%s" % (key, value))

def main():
    # To see messages from networktables, you must setup logging
    global visTable
    global dirty
    nettab = networktables.NetworkTables
    logging.basicConfig(level=logging.DEBUG)
    visTable["count"] = 0
    nettab.initialize()
    nettab.getTable("/SmartDashboard/Vision").addEntryListener(visTargetChanged)
    dirty = False
    i = 0
    while True:
        time.sleep(1)
        i += 1
        if dirty:
            print(visTable)
            dirty = False

if __name__ == "__main__":
    main() 
